apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: h2-database
  template:
    metadata:
      labels:
        app: h2-database
    spec:
      containers:
      - name: h2-database
        image: vansh-pinakin-h2-database:latest
        imagePullPolicy: Never
        ports:
        - name: web
          containerPort: 9081
        - name: tcp
          containerPort: 9082
---
apiVersion: v1
kind: Service
metadata:
  name: h2-database
spec:
  selector:
    app: h2-database
  ports:
  - name: web
    protocol: TCP
    port: 9081
    targetPort: 9081
  - name: tcp
    protocol: TCP
    port: 9082
    targetPort: 9082
  type: ClusterIP
