apiVersion: apps/v1
kind: Deployment
metadata:
  name: walletservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: walletservice
  template:
    metadata:
      labels:
        app: walletservice
    spec:
      containers:
      - name: walletservice
        image: vansh-pinakin-walletservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: walletservice
spec:
  selector:
    app: walletservice
  ports:
  - protocol: TCP
    port: 8082    # Changed from 8080 to 8082
    targetPort: 8080
  type: LoadBalancer

